---
sudo: false
language: c
matrix:
  include:
    - &accept
      os: linux
      env: MODE=deploy3
      services:
        - docker
      script: ./tests/docker-acceptance.sh

    - <<: *accept
      env: MODE=deploy3-bleed

    - <<: *accept
      env: MODE=redeploy

    - <<: *accept
      env:
        - MODE=versiondb
        - VERSIONDB_PUSH=true

    - <<: *accept
      env:
        - MODE=versiondb
        - VERSIONDB_PUSH=false

    # - os: osx
    #   env: MODE=deploy3
    #   script: ./tests/acceptance.sh

    # - os: osx
    #   env: MODE=deploy3-bleed
    #   script: ./tests/acceptance.sh

    - env: TEST=markdownlint
      language: c
      services:
        - docker
      script: ./tests/mdl.sh

    - env: TEST=yamllint
      language: c
      services:
        - docker
      script: ./tests/yamllint.sh

    - env: TEST=shellcheck
      language: c
      services:
        - docker
      script: ./tests/shellcheck.sh
  # osx builds are often very slow to start due to high demand
  fast_finish: true
  # allow_failures:
  #   - os: osx
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
